### PR TITLE
HAD-8830: Adding Support for PySpark in Geo-Addressing SDK

### PR DESCRIPTION
**Pull request by shardul-rajhans-precisely**
Added Guidelines to use PySpark Geo-Addressing SDK for:

1. Databricks Cluster
2. Snowflake Connector for Databricks and EMR

A new directory is created named 'pyspark' containing all the information about Databricks-Addressing and Snowflake Connector.

### CODE REVIEW

**Review by rajveer-singh-01 — COMMENTED** [review]
For snowflake-connector/emr/EMR_PySpark_Addressing_Snowflake_Connector.ipynb file,

`spectrum-bigdata-addressing-sdk-pyspark-5.1.1.0.zip` needs to be changed for version 5.1.0.10

**Review by rajveer-singh-01 — COMMENTED** [review]
For file pyspark/snowflake-connector/databricks)/Snowflake_Connector_Addressing_Demo.ipynb

Change the version 5.1.1.0 to 5.1.0.10

**Review by rajveer-singh-01 — COMMENTED** [review]
For file snowflake-connector/databricks/Snowflake_Connector_Addressing_Demo.ipynb

Change the version 5.1.1.0 to 5.1.0.10

**Comment by PraveenKumarPrecisely** [comment]
All suggested changes are in place.

**Review by PraveenKumarPrecisely — APPROVED** [review]

**Review by rajveer-singh-01 — COMMENTED** [review]
Please replace `your_version` with `<PRODUCT_VERSION>` all the required places (I think 3 places).

`<PRODUCT_VERSION>` indicates that this needs to be replaced with actual version.

**Review by rajveer-singh-01 — APPROVED** [review]
Approve

**Comment by shardul-rajhans-precisely** [comment]
Merging into Dev as PySpark 5.1.0.10 release process is completed.

**Pull request merged**
